#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/tags.$$"' EXIT INT TERM
ign="$dir/.ctagsignore"
touch "$ign"
echo "plugins/\nwww/lib/\nbower_components/\nnode_modules\nhooks/resources/\nscss/\ncoverage/\ne2e/\ngulp/\n">$ign
git ls-files|ctags --tag-relative -L - -f$dir/tags.$$ --languages=-javascript,sql --exclude=@$dir/.ctagsignore
mv $dir/tags.$$ $dir/tags
