#!/bin/sh

# 1.) karabiner
# https://github.com/tekezo/Karabiner-Element
# or if cant download a dmg
# cd ~/docs/dev
# git clone --depth 1 "https://github.com/tekezo/Karabiner-Elements.git"
# cd Karabiner-Elements
# make
# switch caps-lock an escape
# switch fn and left-control
# 2.) Install Chrome
# 3.) Install lastpass
# 4.) XCode Commandline tools
# xcode-select --install
# 5.) add .ssh/config file from dropbox
# 6.) github / ssh keys
# ssh -T git@github.com
# 7.) ./dotfiles.sh
# 8.) change Terminal Preferences to Homebrew profile
# 9.) laptop
# sh laptop 2>&1 
# 10.) install nvm/ npm packages/ etc
# ./post_install.sh
