#!/bin/sh

# 1.) install karabiner
# install Karabiner-elements to change keyboard
# https://github.com/tekezo/Karabiner-Element
# or if cant download a dmg
# cd ~/docs/dev
# git clone --depth 1 "https://github.com/tekezo/Karabiner-Elements.git"
# cd Karabiner-Elements
# make
# 2.) XCode Commandline tools
# xcode-select --install
# 3.) add .ssh/config file from dropbox
# 4.) github / ssh keys
# 5.) ./dotfiles.sh
# 6.) laptop
# sh laptop 2>&1 
# 7.) open vim and :PluginInstall and :VimProcInstall
# 8.) install nvm/ npm packages/ etc
# ./post_install.sh
